#!/usr/bin/env bash
#This installs Nginx on my web-01 server
sudo apt-get update
sudo apt-get install nginx -y
sudo mkdir /var/www/html
sudo touch /var/www/html/index.html
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
